### ISSUE TITLE
HomeView

### ISSUE THREAD

**Issue by steffenhls** [projekt-fitnessapp/frontend#13]

**Comment by Cliff99999** [comment]
Hey Steffen,  anbei nochmal der Screenshot zur Stütze.
LG

![Image](https://user-images.githubusercontent.com/73340782/193591133-24c50963-bd18-42a5-b549-fdaae017dc09.png)

**Comment by Cliff99999** [comment]
Zu testende Funktionalitäten: 
- HomeView - Kalender (Widget)
- Nächstes Training
