### ISSUE TITLE
Trainingsplan Erstellen Screen

### ISSUE THREAD

**Issue by LeonEngelhardt** [projekt-fitnessapp/frontend#23]
![Image](https://user-images.githubusercontent.com/73344519/193609700-2156394f-6cd3-44ae-bd2c-562c1f9ca098.png)

![Image](https://user-images.githubusercontent.com/73344519/193609815-68dee49a-5270-4fb7-9773-5bfe089c77c5.png)

![Image](https://user-images.githubusercontent.com/73344519/193610203-8f63f08b-5202-48c6-a761-cbc811bbcba8.png)

![Image](https://user-images.githubusercontent.com/73344519/193609883-83c120f3-d018-4fac-a134-fdd947a970d6.png)

**Comment by Cliff99999** [comment]
- Button "Trainingsplan Erstellen"
- Auswahl des Trainings Rhythmus
- Screen: Übung Hinzufügen
- Screen: Auswahl Übung
- Filterfunktion - Screen: Auswahl Übung 
- Auswahl des Trainingstools
- Auswahl Tag 1, 2, 3 ....
