### ISSUE TITLE
Training Tracken Screen

### ISSUE THREAD

**Issue by LeonEngelhardt** [projekt-fitnessapp/frontend#25]
![Image](https://user-images.githubusercontent.com/73344519/193611282-d3a5348b-65bc-43d9-9e31-295b8dcdfde9.png)

![Image](https://user-images.githubusercontent.com/73344519/193611345-5a0f034a-c9c5-4d07-af70-cd8716d71412.png)

![Image](https://user-images.githubusercontent.com/73344519/193611458-7caed403-d8f5-41aa-bd0c-29373f7ad76c.png)

![Image](https://user-images.githubusercontent.com/73344519/193611502-72a8f5fc-83e6-4614-a085-4898b2424d15.png)

**Comment by MatthiasBiermanns** [comment]
Feature-Scope ist soweit abgedeckt. Mit Ausnahme der besonderen Satzarten (beachte Anpassung des Feature-Scopes)
