### ISSUE TITLE
Trainingsplan anzeigen/tauschen Screen

### ISSUE THREAD

**Issue by LeonEngelhardt** [projekt-fitnessapp/frontend#26]
![Image](https://user-images.githubusercontent.com/73344519/193607707-595c0574-c4af-4252-91a0-b6c78812ec38.png)

![Image](https://user-images.githubusercontent.com/73344519/193607590-9c673a05-db34-4b5c-abaa-9792f3376caa.png)

![Image](https://user-images.githubusercontent.com/73344519/193607813-cd1a3407-95ff-44e7-8522-c2644458bb66.png)

![Image](https://user-images.githubusercontent.com/73344519/193609526-5e9d7e59-35c0-4d6b-8b81-2ed8dab15ec0.png)

![Image](https://user-images.githubusercontent.com/73344519/193609598-eab20df4-b05e-4c1d-bb91-217668387388.png)

![Image](https://user-images.githubusercontent.com/73344519/193609651-bd0c0a7e-0d56-41c5-a60e-17f4f4fb10a5.png)

**Comment by Cliff99999** [comment]
- Anzeigen der Trainingspläne
- Anzeige der Übungen
- Tauschen des Trainingsplans
