### ISSUE TITLE
[BUG] build failed fronted

### ISSUE THREAD

**Issue by steffenhls** [projekt-fitnessapp/frontend#27]
haben den aktuellen stand auf main geschoben und der build ist fehlgeschlagen. bräuchte da wahrscheinlich eure hilfe
https://github.com/projekt-fitnessapp/frontend/actions/runs/3189699456

**Comment by lumaghg** [comment]
@steffenhls Ich transferiere das Issue in das Frontend Repo, weil der Fehler im flutter run build Befehl auftritt und auch außerhalb des DockerContainers => Somit kein Fehler in der Pipeline, wir helfen natürlich trotzdem gerne wenn es geht :)

**Comment by lumaghg** [comment]
@projekt-fitnessapp/frontend würde euch anbieten einen build-health-check für PRs einzubauen, damit nicht aus Versehen Sachen in den main gemerged werden, die noch große Bugs beinhalten

**Comment by steffenhls** [comment]
Wäre sehr gut.
