### ISSUE TITLE
[BUG] Meine Trainingspläne Liste

### ISSUE THREAD

**Issue by Leersh** [projekt-fitnessapp/frontend#44]
**Was ist passiert:**
Liste der Trainingspläne wird nicht vollständig angezeigt und verschwindet in der Nav Bar. Dadurch können weitere Trainingspläne nicht geladen werden.

**Was sollte passieren:**
Liste soll geladen werden können, damit man alle Trainingspläne anschauen kann.

**Comment by steffenhls** [comment]
Ist schon gelöst, erstelle nachher eine PR
