### ISSUE TITLE
[BUG] Tage der Traingspläne benennen

### ISSUE THREAD

**Issue by Leersh** [projekt-fitnessapp/frontend#47]
**Was ist passiert:**
Bei bereits angelegten Tagen eines Trainings wurden die Namen geändert. War man zurück auf der Übersicht aller Tage, sind die willkürlich verschoben - also der Tag1 namens "A" war dann bei Tag3 bspw. 

**Was sollte passieren:**
Die Reihenfolge der Tage soll beibehalten werden.

**Comment by steffenhls** [comment]
ich schau mir das gleich mal an, kann jedoch auch ein backend fehler sein. würde das dann dementsprechend weiterleiten. danke für den hinweis

**Comment by steffenhls** [comment]
https://github.com/projekt-fitnessapp/backend/issues/97
