### ISSUE TITLE
[BUG] 10RM Calc

### ISSUE THREAD

**Issue by Leersh** [projekt-fitnessapp/frontend#48]
**Was ist passiert:**
bei größeren Zahlen der Wdh und Gewichte, entstehen negative Zahlen bei 10RM.

**Was sollte passieren:**
Es soll der richtige Wert ausgegeben werden.

**Comment by MatthiasBiermanns** [comment]
Bug sollte durch die Anpassung der Gewichts und Wiederholungs-Range behoben sein. Sollte es nochmal auftreten, Issue bitte einfach wieder öffnen!
