### ISSUE TITLE
[FEATURE] Zahnrad Icon während Training

### ISSUE THREAD

**Issue by Leersh** [projekt-fitnessapp/frontend#49]
**Wie ist es aktuell:**
Das Zahnrad-Icon indiziert, dass man etwas einstellen kann, was nicht der Fall ist.

**Wie sollte es sein:**
Passendes Icon zu dessen Funktion einsetzen (z.B. i für Info)

**Comment by MatthiasBiermanns** [comment]
Danke für das Feedback! Wurde angepasst
