### ISSUE TITLE
[FEATURE] Umbenennen von Trainings / Tagen

### ISSUE THREAD

**Issue by Leersh** [projekt-fitnessapp/frontend#50]
**Wie ist es aktuell:**
Man hat keinen Cursor und sieht nicht wo man hinklickt, wenn man etwas umbenennen möchte. Außerdem kann man die Texte nicht markieren, sondern muss es "normal" löschen. Auch das bekannte Enter-Problem, damit Namen gespeichert werden, wurde kritisiert.

**Wie sollte es sein:**
Falls es möglich ist, die drei genannten Aspekte so weit es geht zu verbessern, um die UX zu verbessern.

**Zusätzliche Anmerkungen:**

**Comment by steffenhls** [comment]
Habs auf dem Schirm, wenn noch Zeit ist, fix ich das
