### ISSUE TITLE
[FEATURE] Gewichte bei Trainingsplanerstellung ändern

### ISSUE THREAD

**Issue by Leersh** [projekt-fitnessapp/frontend#51]
**Wie ist es aktuell:**
Man kann beim Erstellen nur Sätze und Wdh einstellen, aber nicht die Gewichte.

**Wie sollte es sein:**
Die Gewichte auch bei der Trainingsplanerstellung schon einstellen können.

**Zusätzliche Anmerkungen:**
Das haben sich bisher die Personen der Tests gewünscht - wie sinnvoll das ist, könnt ihr gerne selbst entscheiden.

**Comment by steffenhls** [comment]
Ist Quatsch aber danke für den Hinweis
