### ISSUE TITLE
[FEATURE] Gewichte und Wdh während Training ändern

### ISSUE THREAD

**Issue by Leersh** [projekt-fitnessapp/frontend#54]
**Wie ist es aktuell:**
Man kann nur bis zu 50kg Gewicht angeben, was wenig ist, aber man kann bis zu 50 Wdh machen, was viel ist.

**Wie sollte es sein:**
Realistische Zahlen bei den beiden Funktionen angeben.

**Comment by MatthiasBiermanns** [comment]
Danke für den Hinweis! Feedback wurde umgesetzt
