### ISSUE TITLE
[TESTING] Generierung der Trainingspläne

### ISSUE THREAD

**Issue by steffenhls** [projekt-fitnessapp/frontend#62]
Wenn [[FEATURE] Automatische Generierung der Trainingspläne](https://github.com/projekt-fitnessapp/backend/issues/86) abgeschlossen ist, bitte ich @TobiasFitzke01 seine View zu testen. Wenn alles wie erwartet funktioniert, kannst du das Issue einfach wieder schließen.

**Comment by TobiasFitzke01** [comment]
Läuft wie geplant
