### ISSUE TITLE
[BUG] Training abschließen

### ISSUE THREAD

**Issue by LeonEngelhardt** [projekt-fitnessapp/frontend#65]
Nach dem Starten eines Trainings kann dieses nicht mit dem Betätigen des Buttons "Training Abschließen" beendet werden. Fehlermeldung "Speichern Fehlgeschlagen" erscheint.

**Comment by MatthiasBiermanns** [comment]
Unseren Wissens nach wurde der Bug bereits gelöst. Bitte schau nochmal nach, ob der Bug immer  noch besteht.
- Falls Nein: Issue bitte schließen
- Falls Ja: bitte mal ein minimal Szenario geben, bei dem das Problem aufgetreten ist. Ich kann den Fehler aktuell nicht rekonstruieren

**Comment by LeonEngelhardt** [comment]
Dann liegt es wahrscheinlich daran, dass ich nicht die aktuellste Version zum Testen verwende.

Es tritt bei mir bei diesem Szenario auf: 
- Drücken auf "Training starten" (egal, ob ich es über die Home-Ansicht mit dem Nächsten Training, oder bei der Meine-Trainingspläne-Ansicht starte)
- Bestätigen/Abhaken aller Sätze (der durchgeführte Tag hat 2 Übungen mit jeweils 3 Sätzen)
- Drücken auf "Training Abschließen"
- Fehlermeldung "Speichern fehlgeschlagen" erscheint

Sollen wir dieses Ticket offen lassen und in einer neueren Version testen, ob der Bug noch auftritt?

**Comment by MatthiasBiermanns** [comment]
Ja gut auf Basis der apk aktuelle Bugs zu beurteilen ist natürlich schwierig. Problem ist bereits gelöst. Ich schließe das Issue.
